### ISSUE TITLE
How to install ssgsea.GBM.classification

### ISSUE THREAD

**Issue by Phoenix12580** [yhoogstrate/gsam#13]
Your paper is excellent, and in the Methods section, I saw that you used ssgsea.GBM.classification R package to evaluate subtypes of glioma. However,I tried to install ssgsea.GBM.classification from GitHub and locally, but I couldn't install it. May I ask how did you solve this?  My R version is R4.2.1 and R 4.1.3
 
Thank you very much

**Comment by Phoenix12580** [comment]
Oh!  Thank you very much for the comments in your script, which helped me solve the problem!

**Comment by yhoogstrate** [comment]
@Phoenix12580 I had difficulties as will figuring it out, here you go:

https://github.com/yhoogstrate/gsam/blob/master/scripts/analysis_ssGSEA.R#L147

**Comment by zds918** [comment]
> 哦！非常感谢您脚本中的评论，它帮助我解决了问题！

请问你是怎么解决这个问题的，我也没法安装
